# Site settings
debug: false
title: 'Datalogic Mobile Computing Developer Community'
tagline: 'Ready for Android?'

encoding: UTF-8
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->

host: 0.0.0.0
baseurl: /xamarin
analytics_tracking_id: 'UA-77632025-1'
samples_url:
  xamarin: 'https://github.com/datalogic/xamarin-samples/tree/master'
  apk: 'https://github.com/datalogic/xamarin-samples/releases/download/v1.0-beta'
